# Site settings
name: Videoage
title: Antonio Trento, theme Jeky New Age, the start Bootstrap themplate build for jekyll
email:
description: A jekyll template for landing pages, portfolio and blogging

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://videoage.github.io" # the base hostname & protocol for your site

#the embed code of the you tube video ex. https://www.youtube.com/watch?v=ePbKGoIGAXY the embed code is:
embed-video: ePbKGoIGAXY
embed-image: 'https://placehold.it/500x500'
secondary-title: grey #the title text color of the secondary color sections (with'' for #hexadecimal value)
secondary-text: '#000000' #the text color of the secondary color sections

head-primary: '#7b4397'
head-secondary: '#dc2430'
theme-primary: '#fdcc52'
theme-secondary: '#fdc539'
theme-dark: '#222'


site.email-btn-bg: black
site.email-btn-txt: white


#Google Ad Sense Data from scripts code (using Google responsive options) and ad client
data-ad-slot: #2973388149
data-ad-client: #ca-pub-9204963049240271
google_ad_client: #ca-pub-9204963049240271

google_analytics: "UA-86331249-1"
addthis_id: ra-5644da281510c62f #you need addthis account to use the left sharing box http://www.addthis.com/
disqus_account: #jeky-new-age put here your disquss short name (only for blog version of the theme)





# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io

#make social-bar true, with the '', if you wanna see the social follow section
social-bar: 'true'

social:
  - title: twitter
    url: https://twitter.com/lantoniotrento
  - title: facebook
    url: https://facebook.com/lantoniotrento
  - title: google-plus
    url: https://plus.google.com/+AntoniotrentoIt
  #- title: github
  #  url: http://github.com/jekyll

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
